server.port = 8443

# -------------------------------------------数据库userinfo连接配置----------------------------------------------------------
# 数据库连接URL
spring.datasource1.url=jdbc:mysql://localhost:3306/userinfo?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&useSSL=false
# 数据库用户名
spring.datasource1.username=root
# 数据库密码
spring.datasource1.password=liu1069823632
# 数据库驱动（java类包）
spring.datasource1.driver-class-name=com.mysql.jdbc.Driver
# 初始化连接大小
spring.datasource1.initialSize=20
# 连接池最小空闲
spring.datasource1.minIdle=10
# 连接池最大使用连接数量
spring.datasource1.maxActive=80
# 获取连接最大等待时间
spring.datasource1.maxWait=60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource1.timeBetweenEvictionRunsMillis=60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource1.minEvictableIdleTimeMillis=300000
# 用来验证数据库连接的查询语句,这个查询语句必须是至少返回一条数据的SELECT语句
spring.datasource1.validationQuery=select 1
# 检测连接是否有效
spring.datasource1.testWhileIdle=true
# 申请连接时执行validationQuery检测连接是否有效。做了这个配置会降低性能
spring.datasource1.testOnBorrow=false
# 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
spring.datasource1.testOnReturn=false
# 是否缓存preparedStatement，也就是PSCache
spring.datasource1.poolPreparedStatements=true
# 指定每个连接上PSCache的大小
spring.datasource1.maxPoolPreparedStatementPerConnectionSize=20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
spring.datasource1.filters=stat,log4j,wall
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录  
spring.datasource1.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true

# -------------------------------------------数据库gameinfo连接配置----------------------------------------------------------
# 数据库连接URL
spring.datasource2.url=jdbc:mysql://localhost:3306/gameinfo?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&useSSL=false
# 数据库用户名
spring.datasource2.username=root
# 数据库密码
spring.datasource2.password=liu1069823632
# 数据库驱动（java类包）
spring.datasource2.driver-class-name=com.mysql.jdbc.Driver
# 初始化连接大小
spring.datasource2.initialSize=20
# 连接池最小空闲
spring.datasource2.minIdle=10
# 连接池最大使用连接数量
spring.datasource2.maxActive=80
# 获取连接最大等待时间
spring.datasource2.maxWait=60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource2.timeBetweenEvictionRunsMillis=60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource2.minEvictableIdleTimeMillis=300000
# 用来验证数据库连接的查询语句,这个查询语句必须是至少返回一条数据的SELECT语句
spring.datasource2.validationQuery=select 1
# 检测连接是否有效
spring.datasource2.testWhileIdle=true
# 申请连接时执行validationQuery检测连接是否有效。做了这个配置会降低性能
spring.datasource2.testOnBorrow=false
# 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
spring.datasource2.testOnReturn=false
# 是否缓存preparedStatement，也就是PSCache
spring.datasource2.poolPreparedStatements=true
# 指定每个连接上PSCache的大小
spring.datasource2.maxPoolPreparedStatementPerConnectionSize=20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  
spring.datasource2.filters=stat,log4j,wall
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录  
spring.datasource2.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true

# --------------------------------redis连接配置----------------------------------------------------------
spring.redis.master.host=localhost
spring.redis.master.port=6379
spring.redis.database=1
spring.redis.password=liu1069823632
spring.redis.pool.maxActive=100
spring.redis.pool.maxWait=5000
spring.redis.pool.maxIdle=50
spring.redis.pool.minIdle=0
spring.redis.timeout=6000


# -------------------------------------------thymeleaf静态资源配置----------------------------------------------------------
# 路径
spring.thymeleaf.prefix=classpath:/templates
# 后缀
spring.thymeleaf.suffix=.html
# 模板格式
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html
spring.thymeleaf.cache=false
#spring.mvc.view.prefix = /
#spring.mvc.view.suffix = .html